image: ubuntu/python
create-pages:
  pages:
    publish: public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install pre-commit
    - pre-commit run --all-files
  script:
    - make all
